apiVersion: apps/v1
kind: Deployment
metadata:
  name: michaela
spec:
  replicas: 1
  selector:
    matchLabels:
      app: michaela
  template:
    metadata:
      labels:
        app: michaela
    spec:
      containers:
      - image: okteto.dev/michaela:latest
        name: michaela
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "2afaa508-8f46-c88f-478e-0b40625b791f"
        - name: Vless_Path
          value: "/vl555uh9"
        - name: Vmess_UUID
          value: "2afaa508-8f46-c88f-478e-0b40625b791f"
        - name: Vmess_Path
          value: "/vm66re76"
        - name: Share_Path
          value: "/v2link"
